[common]
database_engine_dsn = "postgres://postgres:postgres@127.0.0.1:5432/chat"

[common.whitenoise]
root = "static"
prefix = "/static"
autorefresh = true

[common.passwords]
schemes = ["sha256_crypt"]

[common.sessions]
signing_key = "supersecret"


[test]
database_engine_dsn = "postgres://postgres:postgres@127.0.0.1:5432/chat_tests"


[prod.sessions]

[prod.whitenoise]
root = "static"
prefix = "/static"
autorefresh = false
