[common]
database_engine_dsn = "postgres://postgres:postgres@127.0.0.1:5432/chat"

[common.passwords]
schemes = ["sha256_crypt"]

[common.redis]
url = "redis://127.0.0.1:6379"

[common.sessions]
signing_key = "supersecret"
cookie_path = "/"

[common.whitenoise]
root = "static"
prefix = "/static"
autorefresh = true


[test]
database_engine_dsn = "postgres://postgres:postgres@127.0.0.1:5432/chat_tests"


[prod]
database_engine_dsn = "$DATABASE_URL"

[prod.redis]
url = "$REDIS_URL"

[prod.sessions]
signing_key = "$SIGNING_KEY"
cookie_path = "/"

[prod.whitenoise]
root = "static"
prefix = "/static"
autorefresh = false
