[common]
database_engine_dsn = "postgres://postgres:postgres@127.0.0.1:5432/chat"

[common.passwords]
schemes = ["sha256_crypt"]

[common.redis]
url = "redis://127.0.0.1:6379"

[common.sessions]
signing_key = "supersecret"

[common.whitenoise]
root = "static"
prefix = "/static"
autorefresh = true


[test]
database_engine_dsn = "postgres://postgres:postgres@127.0.0.1:5432/chat_tests"


[prod.sessions]

[prod.whitenoise]
root = "static"
prefix = "/static"
autorefresh = false
