#!/usr/bin/env bash

set -eo pipefail

if [ -z "$VIRTUAL_ENV" ]; then
    echo "warning: you are not in a virtualenv."
    exit 1
fi

pip install -U pip pip-tools
pip-compile -U requirements.in
pip-compile -U requirements-dev.in
pip-sync requirements-dev.txt requirements.txt
