#!/usr/bin/env bash

set -euo pipefail

log() {
    echo "$(date) ::" "$@"
}

log "Creating release branch..."
git stash >/dev/null \
    && (git branch -D release || true) >/dev/null \
    && git checkout -b release >/dev/null

log "Generating static assets..."
npm run-script build && python -m whitenoise.compress static

log "Committing assets..."
git add -f static/* >/dev/null \
    && git commit -am 'add static files' >/dev/null

log "Deploying..."
git push -f heroku release:master \
    && git checkout master \
    && git stash pop
